### ISSUE TITLE
Splash screen icon is always default Android Icon

### ISSUE THREAD

**Issue by roneyk** [travelpayouts/travel-app-android#10]
Even we change the icon in splash.xml file with our application icon, nothing reflect in the splash screen.
Please help

**Comment by b1uebyte** [comment]
You don't need to change icon in `splash.xml`. By default it shows `ic_launcher` icon ([how to change app icon](https://github.com/travelpayouts/travel-app-android#app-icons-creation)).

If you want to provide your custom `splash.xml`, don't forget that there are two version of it and you have to change both of them:
* `drawable/splash.xml`
* `drawable-v23/splash.xml`

**Comment by roneyk** [comment]
Done , thanks alot
