### ISSUE TITLE
How I can start this Application only when user click on some link in my main App?

### ISSUE THREAD

**Issue by Bhavana-Util** [travelpayouts/travel-app-android#100]
Hi,

I have imported this project as an Android-Library dependency in my main Android App. 
Now, I am looking to launch this Application on click event.  
I tried several ways but it doesn't work. 

Would you please share some example code how I can achieve this?

**Comment by riveraj33** [comment]
Hi. Did you figure this out? Also, what did you use to import Travelpayouts to your app?

**Comment by Bhavana-Util** [comment]
> Hi. Did you figure this out? Also, what did you use to import Travelpayouts to your app?

No. I couldn't find any documentation when I can make some changes in SDK. I imported travelpoyout project as dependency & there I can add only tabs.

**Comment by tpsupport** [comment]
Hello,

We apologize for the long wait for a response.
The Travel App does not support integration into other projects. It can be used only as a standalone application.

If you have any questions, please contact us by email support@travelpayouts.com
