### ISSUE TITLE
The 'kotlin-android-extensions' Gradle plugin is deprecated. 

### ISSUE THREAD

**Issue by blittir** [travelpayouts/travel-app-android#101]
Please fix error "The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin."

**Comment by tpsupport** [comment]
Hello! Please follow this migration instruction: https://developer.android.com/topic/libraries/view-binding/migration
Should you have any additional questions, feel free to contact us at support@travelpayouts.com.
