### ISSUE TITLE
Add 'android:exported' for <activity>

### ISSUE THREAD

**Issue by bruimafia** [travelpayouts/travel-app-android#105]
If set targetSdkVersion 31 and compileSdkVersion 31 that error showed. Please, add 'android:exported' for activities.

Error: android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for 'android:exported'.

**Comment by tpsupport** [comment]
Hi!

Unfortunately, Android 12 is not supported in this build, but it will in the next version.

**Comment by bruimafia** [comment]
Is that good, thanks!

**Comment by tpsupport** [comment]
You are always welcome!
