### ISSUE TITLE
А на каком ресурсе это надо делать

### ISSUE THREAD

**Issue by Idrak75** [travelpayouts/travel-app-android#106]
Добрый день, друзья. В андроидстудио или где именно делается приложение, не подскажете?

**Comment by mishinivan** [comment]
Да, в студии выбираете get from vcs и указываете адрес репозитория.

**Comment by Idrak75** [comment]
Спасибо большое, мил человек, а нет пошаговой инструкции для чайников как бы?

**Comment by tpsupport** [comment]
Здравствуйте. К сожалению, подробной инструкции по работе с Android Studio у нас нет. Если у вас появятся дополнительные вопросы, будем рады помочь.
