### ISSUE TITLE
Проблемы в релизе 1.4.2

### ISSUE THREAD

**Issue by mishinivan** [travelpayouts/travel-app-android#107]
Привет разработчикам! 
Есть ряд замечаний по релизу:

1.  В отелях на экране выбора города не появляется курсор ввода, то есть он не мигает и не виден вообще, при этом клавиатура активна. В итоге пользователь думает что поле ввода не работает.
2. Корявый русский текст в разделе "О приложении - настройки - единицы измерения", какие-то спецсимволы мусорные вместо пробела в тексте.

И пожелания:

1. Желательно добавить больше цветов в настройках - для фона и иконок отдельные цвета.
2. Возможность компилировать отдельно только билеты и только отели, не загружая неиспользуемый функционал.
3. Позволить строить мультимаршруты в билетах.

Спасибо за внимание, хорошего дня)

**Comment by tpsupport** [comment]
Добрый день! Воспроизведём ошибки и вернёмся с ответом. Что касается пожеланий, к сожалению, не удастся их реализовать: в настоящий момент мы занимаемся только поддержкой проекта, без его дальнейшего развития.
