### ISSUE TITLE
Перестал работать поиск авиабилетов

### ISSUE THREAD

**Issue by Sever-1974** [travelpayouts/travel-app-android#108]
Здравствуйте, вопрос может и не к вам, но больше не у кого спросить. Собранное приложение приложение работало нормально, но перестал работать поиск авиабилетов. Ни ошибок, ни сбоев. При выборе даты полёта подсвечиваются числа (дороже, дешевле), но после нажатия на поиск не долго думает и пишет "Что-то пошло не так, попробуйте позже". Скачал другие приложения на вашем API, у них нормально работает поиск! Адрес "com_travelpayouts_flight_engine_host"  оставил ваш "travel-api.pw". Что посоветуете?

**Comment by tpsupport** [comment]
Здравствуйте! Пришлите, пожалуйста, подробную информацию о своём приложении, включая ссылку на него, на адрес электронной почты support@travelpayouts.com. Проверим, чем может быть вызвана проблема.

**Comment by Sever-1974** [comment]
Прошу извинения за панику! Двое суток не работало, а сейчас ещё раз проверил - снова работает! Ничего не делал, чертовщина какая-то!

**Comment by tpsupport** [comment]
Рады, что проблема решилась! Если у вас появятся какие-либо вопросы, обращайтесь в любое время.

**Comment by Sever-1974** [comment]
Нет, опять началось
https://drive.google.com/file/d/1OM-n_UXgY-1HVVrjRihrwrHQECPe4OML/view?usp=drivesdk

**Comment by Sever-1974** [comment]
Снова заработало. Такая чехарда совсем не на пользу!
