### ISSUE TITLE
New Data safety section in Google Play!

### ISSUE THREAD

**Issue by ggalstian** [travelpayouts/travel-app-android#109]
Hi!
What we should choose in this new section?

I have got messenger from google!
How I can fix the problem?
![272042499_1334053160752871_26293632714752907_n](https://user-images.githubusercontent.com/4472781/151301475-65bd556c-cd0b-474f-87bc-901004893e23.jpg)

**Comment by ggalstian** [comment]
![277933414_327734722590887_5155191868514623020_n](https://user-images.githubusercontent.com/4472781/162588610-147e7254-05f6-4201-b522-baa0c274c371.jpg)

How to solve the problem?

**Comment by tpsupport** [comment]
Hello!

At the moment, the Data safety section is optional. Our developers will prepare instructions on how to provide information for this section by July 2022.
