### ISSUE TITLE
Поиск через Jetradar в место Аviasales

### ISSUE THREAD

**Issue by Sever-1974** [travelpayouts/travel-app-android#11]
Приложение на территории России ищет авиабилеты через Jetradar в место Аviasales.  Пользователи жалуются - в выдаче нет привычных агенств. Посмотрел внимательно скриншоты к программе и у Вас в выдаче лучший вариант это "SmartFares" а не "S7". Как поиск для России переключить на Аviasales?

**Comment by b1uebyte** [comment]
О проблеме знаем, решаем.

**Comment by Sever-1974** [comment]
Хорошо, буду ждать. Спасибо!

**Comment by mishinivan** [comment]
Добавлю - языковые настройки вайтлейбла указанного в качестве эндпойнта и страна выбранная в самом приложении никак не влияют на список агентов в выдаче.

**Comment by Sever-1974** [comment]
Судя по отсутствию коментарий проблема с агентствами решается не просто. Просто из за этого тормозится окончательный релиз. Стоит в скором времени ждать или только с новым обновлением через 3 месяца?

**Comment by b1uebyte** [comment]
@Sever-1974 проверяйте, починили

**Comment by Sever-1974** [comment]
Да, всё супер и даже лучше. Добавились даже некоторые приятные плюшки!
