### ISSUE TITLE
How can I change the title and the button text?

### ISSUE THREAD

**Issue by re1s453** [travelpayouts/travel-app-android#110]
I would like to change the mentioned texts in the hotel-view. How can I do that? Also, in the flight-view, the title at the top is completely missing. Is it possible to display a text like on the hotel-view?
![Screenshot 2022-03-20 225815](https://user-images.githubusercontent.com/101999020/159189032-2c089874-51e1-4541-9975-379fd7a33fee.jpg)

**Comment by tpsupport** [comment]
Unfortunately, this possibility is not provided. All available changes are listed in this article:
https://github.com/travelpayouts/travel-app-android
