### ISSUE TITLE
How can I add a new languages to make SDK support multi languages

### ISSUE THREAD

**Issue by GeorgeNady** [travelpayouts/travel-app-android#111]
I cannot access any of the res folders for make createing a new Locales

**Comment by tpsupport** [comment]
Hi!

Unfortunately, you can't change locals files in the template. 

Travelapp already supports these languages:
Arabic, Danish, German, Greek, English, Spanish, Finnish, French, Indonesian, Italian, Japanese, Korean, Malay, Norwegian, Dutch, Polish, Portuguese, Russian, Swedish, Thai, Turkish, Vietnamese, Chinese, Afrikaans, Estonian, Latvian, Lithuanian, Hindi, Swahili, Filipino (Tagalog).
The language is determined automatically on the user's device. 

Feel free to ask any questions. 
You can always contact us at support@travelpayouts.com
