### ISSUE TITLE
Error with Manifest.

### ISSUE THREAD

**Issue by Achisyg2** [travelpayouts/travel-app-android#114]
Hello, I am trying to upload my application on Playstore but on Play Console I get this error: "You uploaded an APK or Android App Bundle File that has an activity, an activity alias, a service, or a transmission with a intent filter, but the android: exported property is not configured. This file cannot be installed on Android 12 or later. See: developer.android.com/about/versions/12/behavior-changes-12#exported". How do I sole this error?

**Comment by tpsupport** [comment]
Hello,

We don't support Android 12 in the latest version of SDK. The support of Android 12 will be available in the next release. Unfortunately, we can't give you the day it'll be available.

Should you have any additional questions, feel free to contact us at support@travelpayouts.com

**Comment by Achisyg2** [comment]
Oh,
alright. Thank you for your reply. I am waiting for the next release!

**Comment by tpsupport** [comment]
Always glad to help!
