### ISSUE TITLE
monetize app android

### ISSUE THREAD

**Issue by ajervi** [travelpayouts/travel-app-android#115]
It will be possible to monetize the android application, thanks for the good work

**Comment by tpsupport** [comment]
Always glad to help! Should you have any questions, feel free to ask.

**Comment by ajervi** [comment]
how can i monetize the travel-app-android ?

thanks for your help

**Comment by tpsupport** [comment]
Travelpayouts is a CPA (cost-per-action) travel affiliate platform. You get revenue for each booking made by your Travel App users. For more details, see the following article: https://tp.click/2nc.
Let us know if you have any questions.

**Comment by ajervi** [comment]
Thank you for responding and helping, I mean an advertising system for example admod, include advertising in the application, to show ads

**Comment by ajervi** [comment]
I am already an affiliate and I have the application published on google play, I was just asking if it is possible to include advertising within the application.

Thank you for helping.

**Comment by tpsupport** [comment]
Unfortunately, we don't have any ready-made solution for adding ads to the Travel App.

**Comment by ajervi** [comment]
Thanks for helping and responding, it would be interesting to be able to include advertising without being abusive, for example between searches, greetings.

**Comment by tpsupport** [comment]
We are not planning on adding this feature to Travel App in the near future. However, we've added your idea to our users' wishlist for possible future updates.

Should you have any questions, feel free to contact us!

**Comment by ajervi** [comment]
Thank
