### ISSUE TITLE
Travelpayouts Android SDK error

### ISSUE THREAD

**Issue by ozzcell** [travelpayouts/travel-app-android#118]
I am getting the attached error. How can I solve this problem? I updated android studio and kotlin plugins, but the problem is not solved, can you help?

![travel1](https://user-images.githubusercontent.com/23296463/172693219-12d87129-9592-4a56-a8d6-0ac172423e89.png)

**Comment by ozzcell** [comment]
I'm waiting for a solution from you about the solution. Can you help?

**Comment by ozzcell** [comment]
Hi;
When I open the source code in Android studio and generate it, I encounter
the attached errors. I updated Android studio and kotlin, but the problem
still persists. The problem is not solved in the Gradle update. I would
appreciate your help.

  The version of android studio I used.    ( Android Studio Chipmunk
2021.2.1)



Travelpayouts ***@***.***>, 15 Haz 2022 Çar, 10:31 tarihinde
şunu yazdı:

**Comment by tpsupport** [comment]
Hello,

Thank you for the screenshots. Could you please send the APK of your application at support@travelpayouts.com? Our developers will take a look into the situation.

**Comment by ozzcell** [comment]
I can't export the source code APK is not created.  Attached errors occur.

15 Haz 2022 Çar ÖS 6:22 tarihinde Travelpayouts ***@***.***>
şunu yazdı:
