### ISSUE TITLE
Android travel SDK doubt

### ISSUE THREAD

**Issue by roypaul346** [travelpayouts/travel-app-android#12]
Hello,
I have gone through your new android travel SDK, How can i create a standalone hotel or flight app using the given SDK ?. There was such functions on the travel SDK you released for IOS, I didn't found those here on android.

Hopefully waiting for your reply.
Thanks

**Comment by b1uebyte** [comment]
This time we don't provide sdk due to lack of demand. Only template app, which has limited customisation options.

**Comment by b1uebyte** [comment]
Still you can create standalone app. There is only one big limitation of current approach - you can't embed our sdk to your app - you can only create your app from our template app.

**Comment by roypaul346** [comment]
It should be really helpful if you can add such customisation. Just hiding one of the category ( Flight or hotel ) if needed. So we can release a complete hotel booking app in playstore, otherwise people always landing their homescreen on flights. Hope you understood.

**Comment by b1uebyte** [comment]
We have similar idea on our roadmap list

**Comment by roypaul346** [comment]
Thank you. Am waiting for such a release

**Comment by shakesgar** [comment]
About to release a huge app and an SDK would have been great. Currently, I'm using the aviasales SDK for flights and opening my hotel's white-label in chrome custom tabs. Not ideal, but does the job.

**Comment by edubovik** [comment]
@roypaul346 Can you please tell us when do we get standalone sdk?

**Comment by riveraj33** [comment]
Hello. Any update on an android sdk? I'm creating an app with the iOS sdk but need a matching android version.
