### ISSUE TITLE
Please update sdk for your partners

### ISSUE THREAD

**Issue by riveraj33** [travelpayouts/travel-app-android#120]
Hello. Please provide an update for android api 32. We are getting errors and cannot compile to the most recent OS versions. Or are you no longer providing support? Thanks for your work.

**Comment by ggalstian** [comment]
We are waiting for update!

**Comment by appsTBM** [comment]
Ждем обновления!

**Comment by troatly** [comment]
Please update to api 32

**Comment by tpsupport** [comment]
Hello!

Thank you all for your comments.
We will let you know, when we update the app. 

Sorry for the inconvenience caused.

**Comment by troatly** [comment]
> Hello!
> 
> Thank you all for your comments. We will let you know, when we update the app.
> 
> Sorry for the inconvenience caused.

any ETA ? week or months ?

**Comment by tpsupport** [comment]
Unfortunately, there is no approximate time frame yet. As soon as there is news, we will let you know. 

Thanks for understanding.

**Comment by troatly** [comment]
any update ?

**Comment by troatly** [comment]
> Unfortunately, there is no approximate time frame yet. As soon as there is news, we will let you know.
> 
> Thanks for understanding.

any update ?

**Comment by tpsupport** [comment]
@riveraj33 @troatly @ggalstian @appsTBM Hi! We got the timeline from our developers, we are planning to update our SDK to be compatible with Android API 32 approximately in the beginning of 2023.
