### ISSUE TITLE
Your app is not compliant with Google Play Policies

### ISSUE THREAD

**Issue by orgpt** [travelpayouts/travel-app-android#122]
Hi, We need to know how to fix this issue 👍 
SPLIT_BUNDLE 31: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID)

**Comment by tpsupport** [comment]
Hi! You need to accurately complete a Data safety section. You can look at Data safety of our app and use it as a reference: https://play.google.com/store/apps/datasafety?id=ru.aviasales
