### ISSUE TITLE
Привет всем помогите пожалуйста исправить эту недостатки приложения

### ISSUE THREAD

**Issue by appsTBM** [travelpayouts/travel-app-android#123]
Когда загружаю файла aab на маркет появиться такая ошибка: Вы загрузили APK-файл или набор Android App Bundle с объектом activity, псевдонимом объекта, сервисом или широковещательным приемником с фильтром intent, но без набора свойств android:exported. Этот файл нельзя установить на устройство с версией Android 12 или выше. Чтобы узнать больше, перейдите на developer.android.com/about/versions/12/behavior-changes-12#exported.

Код манифест куда и как добавить код  android:exported="true"
<manifest
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        package="com.travelpayouts.travel.app"
    tools:ignore="WrongManifestParent">

    <application
            android:name=".App"
            android:allowBackup="false"
            android:icon="@mipmap/ic_launcher4"
            android:label="@string/app_name"
            android:roundIcon="@mipmap/ic_launcher4"
            android:theme="@style/TravelAppTheme"
            android:largeHeap="true"
            tools:ignore="GoogleAppIndexingWarning" />

</manifest>

**Comment by tpsupport** [comment]
Здравствуйте!

Travelapp в данный момент не поддерживает Android 12. Добавим поддержку в новой версии релиза, но сроков на данный момент нет, к сожалению. 
Можем порекомендовать собрать проект под версию Android 11. 
Если возникнут вопросы, пишите на support@travelpayouts.com.

**Comment by appsTBM** [comment]
Написал на почту
