### ISSUE TITLE
Незашифрованный трафик

### ISSUE THREAD

**Issue by Sever-1974** [travelpayouts/travel-app-android#124]
Это сообщение в Консоле. 
"Незашифрованный трафик разрешен для всех доменов
Настройки сетевой безопасности вашего приложения разрешают незашифрованный трафик для всех доменов. Это может привести к перехвату отправляемых данных. Утечка персональных данных или информации, позволяющей идентифицировать личность, может нарушить конфиденциальность пользователей.

Рекомендуем разрешить только зашифрованный трафик, установив значение "false" для параметра [cleartextTrafficPermitted](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted), или добавить политику шифрования для отдельных доменов."

Посмотрел похожие приложения в Плей Маркете и у всех в разделе "Защита данных" - "Данные шифруются при передаче."
 **Как включить " зашифрованный трафик" в приложении?**
**Если нельзя включить шифрование , то как заполнить раздел "Защита данных" чтоб Гугл не удалил приложение?**

**Comment by dtachkov** [comment]
это поправят?

**Comment by tpsupport** [comment]
В будущем мы выпустим полностью обновленную версию Travel App и постараемся учесть эту особенность в новой версии.
