### ISSUE TITLE
targetSdkVersion 30 to targetSdkVersion 31

### ISSUE THREAD

**Issue by hesham2255** [travelpayouts/travel-app-android#126]
New apps must target Android 12 (API level 31) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target Android 11 (API level 30) or higher.

wheng change targetSdk to 31 i got 

Manifest merger failed with multiple errors, see logs

any temp. solutions?

**Comment by tpsupport** [comment]
Hi,

There is no temporary solution, unfortunately. 
Android 12 devices will be supported in the future, but there are no timelines for now.

Sorry for the inconvenience caused.
