### ISSUE TITLE
ability to show ad similar to IOS

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-android#13]
Hello,

As I see in Android SDK we don't have an ability to show ads , when will you provide that feature ?

**Comment by b1uebyte** [comment]
Hi @patriksharma. It's already in our roadmap list. We're planning the next major update in three months.

**Comment by patriksharma** [comment]
cool @patriksharma . Thanks for update.

**Comment by techblinks** [comment]
It seems its already 3 months,still no updates
