### ISSUE TITLE
Bug in app version 2.0.0 when used Firebase

### ISSUE THREAD

**Issue by Jasper7** [travelpayouts/travel-app-android#134]
I try update my app to version 2.0.0
Everything is fine, except that when you try to search for airline tickets displays an error in Logсat and search does not happen.

Logcat error after click search:
<img width="1728" alt="Screenshot 2023-03-21 at 16 05 51" src="https://user-images.githubusercontent.com/4204036/226615299-bdd29985-6da4-4ae6-84a0-5d2a2a3abafc.png">

App UI after click search:
![photo_2023-03-21_15-52-32](https://user-images.githubusercontent.com/4204036/226615455-dfc3450a-6409-4f07-9d5a-5041840d9c82.jpg)

Can you give feedback or a deadline for when the problem will be fixed?

**Comment by tpsupport** [comment]
Hello there! Thank you for reporting the issue. Our developers are already looking into the problem. We'll let you know as soon as it is fixed.

**Comment by tpsupport** [comment]
Our developers have fixed the issue. Kindly double-check it on your side.

**Comment by Jasper7** [comment]
> Our developers have fixed the issue. Kindly double-check it on your side.

Thanks, Firebase error is missing in Logcat,
but the problem with searching remained, the details are described above

**Comment by Jasper7** [comment]
Problem resolve, thanks)
