### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by Yuice2018** [travelpayouts/travel-app-android#14]
I have already the app for android is there also any documantion about the ios / apple?

**Comment by b1uebyte** [comment]
@Yuice2018 https://github.com/travelpayouts/travel-app-ios

**Comment by Yuice2018** [comment]
Thank you Andrei i never made a app before this android was my first one. So i will dive into the IOS right know.
And Andrei i also want to ask if its possible to ad advertise in android using ad mob?
