### ISSUE TITLE
Почему то приложение называется $application_name

### ISSUE THREAD

**Issue by dtachkov** [travelpayouts/travel-app-android#141]
см/ вложение
В названии приложения в нотификациях и в трее непонятная переменная
Откуда она берется непонятно
![image](https://user-images.githubusercontent.com/111563900/226989130-537f27df-70c9-4cf9-ad61-b3817939becc.png)

**Comment by dtachkov** [comment]
https://disk.yandex.ru/i/DaqvGLBqnt2Opw

**Comment by dtachkov** [comment]
Кстати на вкладке о программе она тоже есть...

**Comment by tpsupport** [comment]
Здравствуйте! Не могли бы вы уточнить название вашего приложения?

**Comment by tpsupport** [comment]
Данная проблема была исправлена в версии 2.0.2. Сообщите, если возникнут дополнительные вопросы.
