### ISSUE TITLE
I cannot Generate Release APK File.

### ISSUE THREAD

**Issue by cagataykyt** [travelpayouts/travel-app-android#150]
The Error is like this:

<img width="1354" alt="Ekran Resmi 2023-05-01 22 51 01" src="https://user-images.githubusercontent.com/45690856/235519617-8e825d88-bd04-46ca-a992-9870abc38e8b.png">

**Comment by tpsupport** [comment]
Hi,

Apologies for the delayed reply.

We’ll handle your request within ticket #154190

**Comment by tpsupport** [comment]
Hi,

Apologies for the delayed reply.

We’ll handle your request within ticket #154190
