### ISSUE TITLE
Не трекаются конверсионные события Firebase

### ISSUE THREAD

**Issue by Jasper7** [travelpayouts/travel-app-android#152]
Проверьте в своей тикет системе Request #154340

Конверсионные события **view_search_results** и **begin_checkout** перестали трекаться
Firebase в приложении подключен, версия SDK 2.0.5

**Comment by tpsupport** [comment]
Добрый день! 

Мы уже работаем над вашим запросом. Вернёмся к вам с новостями в тикете #154340 как можно скорее.
