### ISSUE TITLE
How to fix this problem?

### ISSUE THREAD

**Issue by ggalstian** [travelpayouts/travel-app-android#167]
I want to update app, but not approved. What problem is this?
![img](https://github.com/travelpayouts/travel-app-android/assets/4472781/3ad6cfe7-286f-4684-b173-5224a788157d)

**Comment by tpsupport** [comment]
Hello,

The problem stems from using an outdated version of Xcode in the application template. Unfortunately, we do not have plans to update the current template for compatibility with Xcode 15 at this moment.

However, we've prepared a new template that not only includes many new features, but is also compatible with Xcode 15. You might find this quite beneficial. For more details, please check out our article: [White Label App: a low-code solution for creating your own mobile app](https://support.travelpayouts.com/hc/en-us/articles/17544470681234-White-Label-App-a-low-code-solution-for-creating-your-own-mobile-app).

Should you have any further questions or need assistance, feel free to reach out.

**Comment by ggalstian** [comment]
Your new SDK doesn’t working, there are many problems. When should you fix the problems?

**Comment by Jasper7** [comment]
@tpsupport We're talking about Android, what else is Xcode)

**Comment by ggalstian** [comment]
I'm talking about your new paid SDK (android and ios) . Both have problems,
