### ISSUE TITLE
40MB APK Size!!

### ISSUE THREAD

**Issue by mohamed-fareed** [travelpayouts/travel-app-android#18]
The apk size is 40MB, is there any plans to minimize this? Also i want to ask if there's any plans to make the SDK open source so we can customize the app as we want. Thanks

**Comment by b1uebyte** [comment]
Release apk size is much smaller - 29MB. The size will be even smaller if you use app bundle. But we do have plans to reduce it.

As for open sourcing sdk - we don't have such plans.

**Comment by nowfalsalahudeen** [comment]
no flights results in release apk.only works when minify disabled build

**Comment by b1uebyte** [comment]
Should work now
