### ISSUE TITLE
Did anyone use this repo

### ISSUE THREAD

**Issue by galinei** [travelpayouts/travel-app-android#21]
Hi,
I cannot figure out how I can use the source code. Can anyone explain at least the big steps?
This one (https://github.com/KosyanMedia/Aviasales-Android-SDK) seems to be the right one, but is is official from travelpayouts?
Thanks

**Comment by b1uebyte** [comment]
https://github.com/KosyanMedia/Aviasales-Android-SDK - is official, but not supported anymore.

How to use this repo:
1. Mirror repo
1. Do what's described in readme
2. Get your own app with flights and hotels engine

**Comment by galinei** [comment]
Thanks.
Another two questions:
1) I get an error on the search flights activity ("An error occured while searching. please check your Internet connection. (ConnectionException)") which I saw it was reported one month ago.
2) I want to translate the values.xml strings, but the file attached to another issue is missing a lot of strings from within the app (including the above error message). Could you please supply an updated file?
Kind regards
![search-flights-error](https://user-images.githubusercontent.com/2262305/64389157-1b8ea000-d04a-11e9-827d-1d56397236c7.jpeg)

**Comment by b1uebyte** [comment]
1. Looks like some internet issue. Do you still see this error?
2. We don't recommend to use such kind of translation as it could be broken after by later releases. Which locales are you interested in? Very soon we will add lots of new locales.

**Comment by galinei** [comment]
Hi,
1. The flight search works just fine now, after pulling the last commits.
2. I'm interested in the RO locales
Thanks

**Comment by mjaber82** [comment]
@galinei 
if you are not using the latest release, disable Proguard in app-level/build-gradle.
This issue should be fixed in latest release.

change this :
            minifyEnabled true
            shrinkResources true
to this:
            minifyEnabled false
            shrinkResources false

**Comment by mjaber82** [comment]
I realize that in the latest release, some dependancies are removed (is this normal?) and also some customizations in res/values. I do prefer if we can have the options to fully customize the appearance.
