### ISSUE TITLE
landing on wrong region and currency

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-android#23]
Hello,

I found this an issue where after installing the app in Android phone.

App lands into United kindom as default region and Euro as currency. I think it should be from user current location .

please help me to fix this so user current location will be region and currency in Android.

**Comment by annaTP** [comment]
Hi @patriksharma 
We use system info for region and currency settings in the app. Sim card's data is higher priority, next is device settings. Location is not considered in this case. Could you please tell us more details  why this logic is not suitable for your users?

**Comment by xpatthedon** [comment]
Hi @annaTP currency settings should give a provision for custom currency settings because we have different promotion strategies,preference  and targets. For instance i would prefer my users to view rates in United States Dollars but not the Local currency.
