### ISSUE TITLE
Ticket search server error. Please try again later (code 403)

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-android#24]
> Ticket search server error. Please try again later (code 403)

I'm getting this error when I try to create release build, working fine if I create debug build.

**Comment by b1uebyte** [comment]
Hey @patriksharma, 

We will fix it soon, but for now you can turn off proguard for release builds. Check this comment for details:
https://github.com/travelpayouts/travel-app-android/issues/22#issuecomment-529258411

**Comment by patriksharma** [comment]
Hope it won't effect anything in the App or should I wait for next release (code) before updating the app in play store ? @b1uebyte  .. Please confirm
