### ISSUE TITLE
Error import project in Android studio

### ISSUE THREAD

**Issue by mishinivan** [travelpayouts/travel-app-android#3]
<img width="988" alt="Снимок экрана 2019-07-26 в 15 51 40" src="https://user-images.githubusercontent.com/48008990/61952782-764dca00-afbd-11e9-935e-4951692a5259.png">

**Comment by b1uebyte** [comment]
@mishinivan can you check one more time? It works for me now.

**Comment by mishinivan** [comment]
If use proxy - works!
