### ISSUE TITLE
Some things to correct

### ISSUE THREAD

**Issue by RoberMS** [travelpayouts/travel-app-android#31]
- The search hotel button now shows "The best hotel deals", can you put "Find hotels" as it was before?
- If possible, also remove the title from the hotel search box, or put it in the flight search box, so that both are equals.
- In the flight search box when clicking on select passengers, the color is not applied to the buttons, however in the hotel search box when selecting guests if you apply the color correctly.
- in build.gradle project, show the following warning "kotlin version that is used for building with Gradle (1.3.50) differs from the one bundled into the IDE plugin (1.3.41)", please match the versions.

Thanks.

**Comment by andrewnortonscott** [comment]
I agree with @roberms on this. Especially the ‘The best hotel deals’, at least similar to the iOS SDK have the ability to change the default titles in buttons etc.
