### ISSUE TITLE
Outdated Google Play Developer API Version

### ISSUE THREAD

**Issue by FredRDewitt** [travelpayouts/travel-app-android#35]
Hello, I have getting this warning on my google play developer account in the app dashboard section , how to fix this?

" We've detected that your app is using an old version of the Google Play Developer API. From December 1 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date. Note that this is not related to the AIDL/Billing Library deprecation. [Learn more](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html) "

-travel app android v1.1.6

**Comment by b1uebyte** [comment]
@FredRDewitt some third party library uses it. No need to worry, we don't use Google Play Developer API.
