### ISSUE TITLE
Monetization

### ISSUE THREAD

**Issue by justyce2** [travelpayouts/travel-app-android#36]
Nice work guys.  how soon are we expecting a release with the ability to monetize the app with ad networks.

**Comment by mimikria** [comment]
+
appodeal?

**Comment by tpsupport** [comment]
Hi!

Sorry for late reply. 
We have Appodeal service installed on our Travelapp: https://prnt.sc/x4rv3s
You can find more details in readme file: https://github.com/travelpayouts/travel-app-ios/blob/master/README.md
