### ISSUE TITLE
Disable flights tab

### ISSUE THREAD

**Issue by taziz23** [travelpayouts/travel-app-android#39]
Is it possible to disable flights tab to show only hotel search?

**Comment by b1uebyte** [comment]
It will be available in next major release (hopefully this year)

**Comment by techblinks** [comment]
How can i customise the home UI and change it to something i want..

**Comment by taziz23** [comment]
Hello. Any updates on when the next version will be released?

**Comment by taziz23** [comment]
Is this project dead?

**Comment by maxuna14** [comment]
please release new version with more features. Thank
