### ISSUE TITLE
Launch the app

### ISSUE THREAD

**Issue by ManuchekhrT** [travelpayouts/travel-app-android#40]
Hi!
I have questions about how to launch this app in order to test it and may be add some custom styles and logo?
At least I need to launch it first?

**Comment by annaTP** [comment]
Hi @ManuchekhrT 
You can find all insctructions here: https://github.com/travelpayouts/travel-app-android/blob/master/README.md

**Comment by ManuchekhrT** [comment]
ok, thanks
Actually i could run it, but now I have questions about custom style this app, for example change logo, colors, add images. Can I do that?

**Comment by annaTP** [comment]
@ManuchekhrT sure, you can do it following the manual via the link above.

**Comment by ManuchekhrT** [comment]
> @ManuchekhrT sure, you can do it following the manual via the link above.
