### ISSUE TITLE
No java code

### ISSUE THREAD

**Issue by hiteshbhai** [travelpayouts/travel-app-android#45]
In app no java code so how to make app any suggestion for this please tell me

**Comment by tenetko** [comment]
Travelpayouts Travel Android App is a template that allows to create Android applications for flights and hotels search in your own style. For that reason, it does not contain java files.

You can use this template as a base for your own application, or you can use it "as is", changing only the main settings (app title, color scheme, icon, etc).

**Comment by TMDroid** [comment]
@tenetko I understand but can we please also have the Java classes so we can integrate it in our own apps? Because it's impossible to integrate at the moment
