### ISSUE TITLE
Please add Progress Bar Like in a Travel App iOS

### ISSUE THREAD

**Issue by FredRDewitt** [travelpayouts/travel-app-android#51]
Hello,
Please add  Progress Bar when searching for flights, Like in a Travel App iOS

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-20 at 14 01 41](https://user-images.githubusercontent.com/45330656/74983444-4fae1f80-5436-11ea-9c3d-3b2c4e8d4cf3.png)

**Comment by tpsupport** [comment]
Hello,
We asked the developers to add a progress bar in one of the future releases.
