### ISSUE TITLE
App Build Error

### ISSUE THREAD

**Issue by asifashi1** [travelpayouts/travel-app-android#52]
C:\Users\etc_\.gradle\caches\transforms-2\files-2.1\dd8881240ddfea6e69594921f1b3783e\jetified-as-core-legacy-1.1.6\res\values\values.xml:1183:5-1185:23: AAPT: error: resource attr/passengerType (aka com.travel.app:attr/passengerType) not found.

**Comment by tpsupport** [comment]
Could you check that your Gradle plugin version is specified as `3.5.0` in your `/build.gradle`? I.e.:
```classpath 'com.android.tools.build:gradle:3.5.0'```
