### ISSUE TITLE
can anyone provide me full source code of android studio for this travelpayouts app , both flights and hotels

### ISSUE THREAD

**Issue by krishna143singh** [travelpayouts/travel-app-android#54]
dear sir i am travel agency instructor and under my more then 1000 + travel agents working now , so i want to make travelpayouts api based android app for hotels and flights , if any one provide me full source code then i can give gift him ,, thank you very much , god bless you , my email growupbusinessinfotech@gmail.com.. you can mail me full source code , I just used which on git hub but in this source code java and layout file missing .. so please provide me full source code

**Comment by tpsupport** [comment]
Hello,
Unfortunately, at the moment, all we can share for Android is already shared in this repository. We don't have a version with ready-to-use Java classes and layouts. If you'd like to create your own Android app, you can develop it from scratch using our [Hotels and Flights Search API](https://support.travelpayouts.com/hc/en-us/categories/200358578-API-documentations). Please contact support@travelpayouts.com for more details.
