### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by ggalstian** [travelpayouts/travel-app-android#55]
http://prntscr.com/s27lh6

**Comment by krishna143singh** [comment]
sir can you give me full source code of travelpayouts api based apps ??

**Comment by tpsupport** [comment]
Hello,
In the string
```classpath 'com.android.tools.build:gradle:3.6.0'```
replace `3.6.0` with `3.5.0`.

**Comment by ggalstian** [comment]
Thank you!
