### ISSUE TITLE
Again Today you forgate layout file in this updates so sad , i think you have no great developer , 

### ISSUE THREAD

**Issue by krishna143singh** [travelpayouts/travel-app-android#57]
today i see your latest update and car rental tab , but in this update you are not disclose where i got car rental prgram link , and where can i paste this , and also your developer again forgate that to make layout file , activity_main.xml so sad , if you want to get more traffic and very high sell so you should make ready to use android app source , because many person selling your source code on fiverr om high price , and needy person cant buy your ready to use source code , you should make available ready to use source code for public to make great traffic and great sell , you should think about this business strategy to make your travel payouts business profitable , i this plateform your developer dont want to make travelpayouts android app source code ready to use , because all your developer sell your source code on fiverr at price , selling the source in black market ,  I want to write a letter to travelpayouts CEO , and founder that travelpayouts developer doing only formalty on github to provide source code but that source code not working because lake of file ,. after asking about file of layouts , developer reply that you should make yourself , but no one understand tgat if every person can make himself then why are you provide here source code , you should not provide here , i will complain to travelpayouts founder againts developer ,

**Comment by tpsupport** [comment]
Hello,

I'm Michael from Travelpayouts support. I'm not a developer. I can confirm what has been said earlier: we don't provide Java classes and layouts, as well as `activity_main.xml`.

What we provide is as follows. We have a hassle-free template for those affiliates who are willing to quickly build an app without going deep into classes, methods, and layouts. That's what is shared in this repository.

Also, we have a full-scale Search API. Affiliates who are familiar with Java/Kotlin and Android Studio develop their own classes and methods that send and process API queries. They also develop their own layout to make their applications unique.
