### ISSUE TITLE
Не работает Rentalcars и firebase

### ISSUE THREAD

**Issue by Sever-1974** [travelpayouts/travel-app-android#60]
Здравствуйте, в поиске автомобиля не получается выбрать - Страну, город и место из выпадающего списка, просто не реагирует на нажатие. При снятии комментария с  //apply plugin: 'com.google.gms.google-services'и //apply plugin: 'com.google.firebase.crashlytics и //classpath 'com.google.gms:google-services:4.3.1 получаю такую ошибку: Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'com.google.firebase.crashlytics' not found.

**Comment by annaTP** [comment]
Здравствуйте,

Уже тестируем фикс, в ближайшее время выложим релиз.

**Comment by annaTP** [comment]
Релиз готов: https://github.com/travelpayouts/travel-app-android/releases/tag/1.2.2

**Comment by Sever-1974** [comment]
Спасибо, Rentalcars заработал!, но с firebase всё по прежнему печально. При компиляции выскакивает куча Важных предупреждений. P. S. Если в приложении сделать несколько переключений по вкладкам, то после невозможно уже выйти из прилодения! Просто обнавляется экран, но приложение не закрывается.

**Comment by annaTP** [comment]
Спасибо за ответ! Вы могли бы прислать скриншоты предупреждений, а также скринкаст проблемы с переключением вкладок нам на support@travelpayouts.com?
