### ISSUE TITLE
WORST DEVELOPER IN GITHUB - TRAVELPAYOUT

### ISSUE THREAD

**Issue by patriksharma** [travelpayouts/travel-app-android#61]
are you guys serious ? 

You guys are releasing a build without testing then you don't even reply for issues with in 24 hours? what do you expect from other github developers .. that they should make an buggy update in there apps from your update.

Come on Travelpayout team, Do check your updates before making it to public

**Comment by yanchuk** [comment]
Hi! Bugs happen and of course our team tests builds before releasing. Meanwhile, please wait for a reply from our support team. Also, the best way to report bugs is also open a support ticket at Travelpayouts.

And please, don't claim our developers as "the worst". You are always free to use our API and build your app yourself at your own. It takes huge investments for us to update this product. 

You'll get a reply from our team next week.

Stay safe!

**Comment by patriksharma** [comment]
> Hi! Bugs happen and of course our team tests builds before releasing. Meanwhile, please wait for a reply from our support team. Also, the best way to report bugs is also open a support ticket at Travelpayouts.
> 
> And please, don't claim our developers as "the worst". You are always free to use our API and build your app yourself at your own. It takes huge investments for us to update this product.
> 
> You'll get a reply from our team next week.
> 
> Stay safe!

Understood and sorry for being so harsh with Subject and comments. I Do understand that developers are working really hard and we are not even paying them for doing these releases. 

I wrote it because :
1. I have raised for adding ads framework in Android platform last year and it was mentioned at that time, we will add it in next release.
2. Our last update do have addition of Firebase so Take a case here, We have last update in play store with Firebase integrated. Now the release you gave with Cabs option but we were unable to run using firebase. Now without firebase we were unable to update our app.

So hope that explains it. Sorry once again.
