### ISSUE TITLE
Ignore languages

### ISSUE THREAD

**Issue by Dipdive** [travelpayouts/travel-app-android#63]
How can I make sure that changing the system language won't change the app language? I have made a custom strings.xml translation and don't want it to update when the user's language is changed. I want it to always be English.

How can I do that?

Thanks.

**Comment by tpsupport** [comment]
Hi @Dipdive
I'm afraid we do not support a single locale install. You can try other developers' solutions, but we don't guarantee how it'll work. Here's an example:
https://stackoverflow.com/questions/2900023/change-app-language-programmatically-in-android

Hope it helps.
