### ISSUE TITLE
Overwrite playstore URL

### ISSUE THREAD

**Issue by shakesgar** [travelpayouts/travel-app-android#65]
Hi,

How do we change the URL for your apps PlayStore listing?

Currently, in the settings menu, there is a link to the playstore but I cannot see where to add this link in the project!

**Comment by tpsupport** [comment]
Hi! 

You should place your itunes_link to the default_config.plist

**Comment by shakesgar** [comment]
> Hi!
> 
> You should place your itunes_link to the default_config.plist

Itunes? This is an Android app! This question is posed in the travelpayouts travel-app-**android**

How to I replace the emplty link for the apps listing in the Google PlayStore?

**Comment by tpsupport** [comment]
Sorry, all you need to do is change applicationID in app/build.gradle file. Here's how to implement it: https://github.com/travelpayouts/travel-app-android#application-id
