### ISSUE TITLE
 Default Activity not found

### ISSUE THREAD

**Issue by sheetal-codebrew** [travelpayouts/travel-app-android#66]
All we are working with the app class. There is only one class in whole project the App.kt, I don't know how is it working, but our project needs a default class to start. It is saying...
Could not identify launch activity: Default Activity not found
Error while Launching activity

How to resolve this, do I need to create an empty launcher activity or something else,
I'm testing on Honor play 9.0

**Comment by tpsupport** [comment]
Thank you for bringing this to our attention. We have reproduced the issue and have put a task to fix it. 
You can't launch the app automatically on Android Studio 4.0, but it will install and work. To make the automatic installation work, you can do the following (optional one of the following steps): 

- Install Android Studio 3.6.3 and remove library version updates.

- Switch to the [fix-default-activity branch](https://github.com/travelpayouts/travel-app-android/pull/67/files) - a temporary fix is available there.

- Wait for the fix to come out. We don’t have exact dates unfortunately. We will create a task and fix it as we deal with the current one.

**Comment by shakesgar** [comment]
Any idea when this will be sorted? Thanks

**Comment by fniyazi** [comment]
يمكنني توفير كود برمجي للبحث عن الرحلات والفنادق

**Comment by tpsupport** [comment]
> Any idea when this will be sorted? Thanks

We expect the issue to be fixed in the next Android Studio version.
