### ISSUE TITLE
Is this template modifiable?

### ISSUE THREAD

**Issue by ilasisi** [travelpayouts/travel-app-android#7]
I can't seems to modify this template by adding my logo and the likes

**Comment by b1uebyte** [comment]
@ilasisi have you cheched up the [App icons creation](https://github.com/travelpayouts/travel-app-android#app-icons-creation) section in documentation?

**Comment by ilasisi** [comment]
Yes but I am talking about adding my logo at the search screen or adding
additional menu option

**Comment by b1uebyte** [comment]
Sorry. Not supported yet. I will discuss your suggestions with team.

**Comment by ilasisi** [comment]
Ok! Maybe I will still stick to Aviasales SDK for now

**Comment by reganold** [comment]
Would be glad if we can put our own logo, at least at the front page, on top of search form.

Thank You
