### ISSUE TITLE
Custom splash color and logo

### ISSUE THREAD

**Issue by koziejakub** [travelpayouts/travel-app-android#73]
Hi - how to change the background and insert the logo into the splash in the application? Are you going to introduce a price alert function?

**Comment by tpsupport** [comment]
Hello!

Sorry for delay in answer.
1. You should change ic_launcher_background.xml and ic_launcher_foreground.xml to your own. You can find these files in recources (travel-app-android/app/src/main/res/drawable);
2. Unfortunately, we won't introduce price alerts in the near future.

Feel free to ask any questions.

**Comment by s9iper1** [comment]
is there a way to reduce splash screen  timeout ?

**Comment by tpsupport** [comment]
Hello!

Sorry for late reply.
Unfortunately, you can't reduce splash screen timeout. There's no delay in splash screen, it shows only while app is loading.
