### ISSUE TITLE
Urgent problem

### ISSUE THREAD

**Issue by koziejakub** [travelpayouts/travel-app-android#79]
Please update play core to the latest version. If you do not do this I will not be able to send you any more updates to my application in 90 days.

**Comment by Sveshlex** [comment]
They don't understand what this is about! Or they don't care!

**Comment by tpsupport** [comment]
Hello,

We apologize for not getting back to you earlier. We are going to update Travel App till the end of this month.

**Comment by Sveshlex** [comment]
> Привет,
> 
> Приносим извинения за то, что не связались с вами раньше. Мы собираемся обновить приложение Travel до конца этого месяца.

It's good that not until the end of this year!

**Comment by tpsupport** [comment]
@koziejakub please check our update: https://github.com/travelpayouts/travel-app-android/releases/tag/1.3.8
