### ISSUE TITLE
Add Fragment or Activity within Existing app

### ISSUE THREAD

**Issue by zaigham-sadad** [travelpayouts/travel-app-android#80]
We do have our existing application available. And we want to give options for our user with travel payout sdk.

Is there any possibility we can directly add Fragment or activity within existing app based on some action.

We have TabLayout used in app and Even if there is possibility we can add tab to our existing tab-layout.

**Comment by tpsupport** [comment]
This option is not available for Travelpayouts Travel App at this moment.

**Comment by zaigham-sadad** [comment]
@tpsupport  can you please provide other option like , share us api details so that we can show it on our own fragment.

**Comment by tpsupport** [comment]
@zaigham-sadad you can request access to API via email at support@travelpayouts.com and provide details about your existing app in which you are planning to integrate it.
Here is API documentation: https://travelpayouts.github.io/slate/#flights-search-api-real-time-and-multi-city-search
