### ISSUE TITLE
Out of memory: GC overhead limit exceeded.

### ISSUE THREAD

**Issue by nadeer2004** [travelpayouts/travel-app-android#84]
How to solve this issue
<img width="1847" alt="Screenshot 2021-04-08 at 11 28 46" src="https://user-images.githubusercontent.com/66866168/113975917-dbaf2080-985d-11eb-9585-7e584dcc1845.png">

**Comment by tpsupport** [comment]
@nadeer2004 try increasing the memory limit in the project's **gradle.properties** file and let us know if it helps.
![image](https://user-images.githubusercontent.com/62344027/113996214-a4417380-985f-11eb-82d4-dce2653aaa66.png)

**Comment by nadeer2004** [comment]
Thank you.

**Comment by nadeer2004** [comment]
Its not working

**Comment by tpsupport** [comment]
@nadeer2004 Hi, could you please send us your hardware specifications?

**Comment by nadeer2004** [comment]
i am using mac book

**Comment by nadeer2004** [comment]
i have used 1.3.9 version also . but giving same result

**Comment by nadeer2004** [comment]
<img width="1920" alt="Screenshot 2021-04-16 at 22 07 16" src="https://user-images.githubusercontent.com/66866168/115056197-28e75e00-9f00-11eb-80e7-73f4ddf83303.png">

**Comment by nadeer2004** [comment]
this is  happening again

**Comment by tpsupport** [comment]
@nadeer2004 thank you for providing this screenshot. However, we still need the specifications of your MacBook (RAM, etc.), could you please send them?

**Comment by nadeer2004** [comment]
macbook 2015 16 gb ram

**Comment by nadeer2004** [comment]
<img width="250" alt="Screenshot 2021-04-16 at 22 40 18" src="https://user-images.githubusercontent.com/66866168/115059832-ba58cf00-9f04-11eb-8b53-1d90daa4cdab.png">

**Comment by nadeer2004** [comment]
is there any instant messaging platform with which I can contact you? Like Whatsapp

**Comment by tpsupport** [comment]
Thank you! We've passed it to our developers.
We can continue to communicate here or you can contact us on support@travelpayouts.com 
Where would it be more convenient for you?

**Comment by nadeer2004** [comment]
hello,

**Comment by nfnc1985** [comment]
hello! we will come with the solution soon!

**Comment by amjad07** [comment]
hey 
I am getting the same problem
my specs are 20 GB ram 7th gen core i5 lenovo

**Comment by nadeer2004** [comment]
> hey
> I am getting the problem
> 
> Out of memory: GC overhead limit exceeded. Please fix the project's Gradle settings.
> my specs are 20 GB ram 7th gen core i5 lenovo

<img width="376" alt="Screenshot 2021-04-21 at 14 27 06" src="https://user-images.githubusercontent.com/66866168/115526460-b08cee00-a2ad-11eb-8ea7-231fd631f755.png">
change this to 1024 , And update all plugins to the latest version. After multiple attempts, I was successful in building code 1.3.9.  If you prefer to have more discussion on tp SDK feel free to contact at nadeer2004@gmail.com.

**Comment by tpsupport** [comment]
Hello, @nadeer2004!
Thanks for the message. 

@amjad07, Hi!
If the method above doesn't work, feel free to contact us.

**Comment by nadeer2004** [comment]
> Hello, @nadeer2004!
> Thanks for the message.
> 
> @amjad07, Hi!
> If the method above doesn't work, feel free to contact us.

Thank you very much for your quick response. Your solution made my work easier

**Comment by tpsupport** [comment]
@nadeer2004 You are always welcome!

**Comment by amjad07** [comment]
Hi
@tpsupport 
I am using the travelpayout version 1.3.9 and I tried @nadeer2004  solution by modifying the line

org.gradle.jvmargs=-Xmx1024m

after this, I tried to make a release .aab file but unfortunately, my Gradle is still running not able to make the .aab file.

can you please help me further to fix the issue?

many thanks

**Comment by amjad07** [comment]
here is the snap
![image](https://user-images.githubusercontent.com/26897162/115635543-634c6300-a325-11eb-8411-506310aee995.png)
![image](https://user-images.githubusercontent.com/26897162/115635572-73fcd900-a325-11eb-9191-a2f86efb1821.png)

**Comment by tpsupport** [comment]
Hello! We recommend increasing the amount of memory.
If you have any questions, please write to support@travelpayouts.com
