### ISSUE TITLE
change botton cloro

### ISSUE THREAD

**Issue by ha-group2020** [travelpayouts/travel-app-android#85]
I modify the color of the button, but it does not change, and also when I click on the Region the app close and i need to know how solve the problem in the screenshot  <style name="TravelAppTheme" parent="AppThemeBase">
![222](https://user-images.githubusercontent.com/66563759/114018706-36547680-9876-11eb-82e1-04c92b33c246.png)

**Comment by tpsupport** [comment]
Hi @ha-group2020, we have fixed the issue with color change and Region in the new release: https://github.com/travelpayouts/travel-app-android/releases/tag/1.3.8

As for the problem on the screenshot, we plan to fix it in the future, however it's a minor problem, and you can disregard it for now.

**Comment by ha-group2020** [comment]
thanks
