### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException lateinit property ticketDependencies has not been initialized

### ISSUE THREAD

**Issue by paradisthomass** [travelpayouts/travel-app-android#89]
App crash

Travel App Android 1.3.9
Android 10 and 11

Crash log:

Fatal Exception: kotlin.UninitializedPropertyAccessException
lateinit property ticketDependencies has not been initialized
ru.aviasales.screen.ticket.presentation.TicketFragment.createComponent (TicketFragment.kt:172)
ru.aviasales.screen.ticket.presentation.TicketFragment.onCreate (TicketFragment.kt:60)
androidx.fragment.app.Fragment.performCreate (Fragment.java:2938)
androidx.fragment.app.FragmentStateManager.create (FragmentStateManager.java:475)
androidx.fragment.app.FragmentStateManager.moveToExpectedState (FragmentStateManager.java:278)
androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:2189)
androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:2100)
androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:2002)
androidx.fragment.app.FragmentManager$5.run (FragmentManager.java:524)
android.os.Handler.handleCallback (Handler.java:914)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:224)
android.app.ActivityThread.main (ActivityThread.java:7560)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

https://user-images.githubusercontent.com/81306421/115703983-0f646d00-a36b-11eb-8265-2ddd826371c0.mp4

**Comment by tpsupport** [comment]
Hello,

We will fix this error in the next travel-app-android SDK update.
If you have any questions, please write to support@travelpayouts.com
