### ISSUE TITLE
Do you plan to release an editable SDK?

### ISSUE THREAD

**Issue by RoberMS** [travelpayouts/travel-app-android#9]
When I saw that you had finally released a sdk of hotels for android, we were glad.

But this joy has lasted for a short time, when seeing the format in which you have taken it out.

A library so closed and not very customizable is totally unfeasible for many of us who have an advanced project and in which we have spent a lot of time invested.

We hope you reconsider, meanwhile, it will be necessary to continue using the old SDK without the hotels.

Regards.

**Comment by braisel** [comment]
agree, I like the hotel search support, but I dont like that strings are not editable, please attach them in the local sdk. Also would be nice if the sdk would be a little bit more customizable, otherwise all projects will look the same more or less.

**Comment by b1uebyte** [comment]
@RoberMS For now we do not plan to provide SDK for Android. If there will be many requests, we will consider developing it.

We will provide more ways for customisation in coming months.
