### ISSUE TITLE
Error on release build

### ISSUE THREAD

**Issue by Oxko** [travelpayouts/travel-app-android#91]
Hi, i get the below error message when building release version of the project 
Execution failed for task ':app:shrinkReleaseRes'.

Debug works fine. Please advise. Thanks.

<img width="1184" alt="Screenshot 2021-04-27 at PM 11 17 07" src="https://user-images.githubusercontent.com/78652916/116313912-b2bfe280-a7ae-11eb-8476-b15deefa9d4b.png">
<img width="1075" alt="Screenshot 2021-04-28 at AM 2 02 17" src="https://user-images.githubusercontent.com/78652916/116326855-c591e180-a7c5-11eb-9bbf-49482cc3667f.png">

**Comment by Sveshlex** [comment]
@Oxko Don't waste your time with this app. My questions have not been resolved for about two months!

**Comment by tpsupport** [comment]
Hello! Sorry for not getting back to you earlier.
We kindly ask you to send us the project code so that we could look into the issue.

**Comment by tpsupport** [comment]
This problem was taken into account as a priority. As soon as the issue is resolved, we will let you know.
If you have any questions, please write to support@travelpayouts.com
