### ISSUE TITLE
JCenter will be shunt down!

### ISSUE THREAD

**Issue by Shvet** [travelpayouts/travel-app-android#93]
I have check ond bintray they are going to stop jcenter and it is already giving error when i run your app. I think jetradar sdk is on jcenter and i tried to find it on [search.maven.org](https://search.maven.org/search?q=jetradar) but didnt find it. 

I would like to know if there will be any update on it any time soon as i need to upload new version of my app on play store

**Comment by tpsupport** [comment]
This problem was taken into account as a priority. The issue will be resolved within a couple of weeks.
If you have any questions, please write to support@travelpayouts.com

**Comment by Shvet** [comment]
Thanks for your response, Just waiting for your update, till then i can not update my app to play store.

**Comment by tpsupport** [comment]
We got a response from the developers, they fixed the bug asking you to do a git pull.

**Comment by Shvet** [comment]
@tpsupport I do not need git pull, I am using gradle to pull your sdk, In which  ` maven { url 'https://dl.bintray.com/jetradar/maven' }` need to be changed to other repo url. Let me add you errors too.


```
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.hotellook:android-api:45.3.
     Required by:
         project :app > com.travelpayouts:travel-sdk:1.3.9 > com.travelpayouts:hotels-core-network:1.3.9
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
      > No cached version of com.hotellook:android-api:45.3 available for offline mode.
   > Could not resolve com.smartlook.recording:app:1.7.0-native.
     Required by:
         project :app > com.travelpayouts:travel-sdk:1.3.9 > com.travelpayouts:flights-booking-assisted:1.3.9
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.
      > No cached version of com.smartlook.recording:app:1.7.0-native available for offline mode.

```

I have also tried it in online gradle synce but not working.

**Comment by Shvet** [comment]
@tpsupport any update?

**Comment by Shvet** [comment]
Yes, It solved the problem of hotellook sdk but, you guys have used [TypedValue](https://github.com/YuriDenison/typedvalue) sdk which is still on jcenter and it is still causing problem to create apk. please try to run above url in your sample project.

**Comment by tpsupport** [comment]
Hello!

We'll check it with our developers and come back to you with the answer soon.

**Comment by Shvet** [comment]
@tpsupport  It started working, Thanks for your help!
