### ISSUE TITLE
When changing region in setting to another country, currency is not changing and few other Questions!

### ISSUE THREAD

**Issue by Shvet** [travelpayouts/travel-app-android#99]
Hello,

1. I have tried to change regions from US to India but currency is not changing with change of region, is it default behavior of setting?

2. I want to add lottie animation for my splash screen is it possible in newer versions?

**Comment by tpsupport** [comment]
Hello,

1. Yes, this is the default behavior. When you change the region, the currency does not change automatically.
2. Unfortunately, we do not have such an opportunity yet.

If you have any questions please email us support@travelpayouts.com

**Comment by Shvet** [comment]
Can i add my own splash screen? @tpsupport

**Comment by tpsupport** [comment]
Hello,

Yes, you can add your own splash screen by replacing the splash.xml files in the project with your own.

**Comment by Shvet** [comment]
Hello, Thank you for your reply I would like to use Lottie Animation with my own splash screen. so i may need to start with creating activity, i have checked your document but there is no mention for something to add new activity in app before your sdk's activity get called

**Comment by tpsupport** [comment]
Hello,

We apologize for not getting back to you earlier.

As we mentioned in the first reply, it isn't possible to add Lottie Animation at the moment. Unfortunately, you can't add a custom activity.
